// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpE0kJ6j9HN-Y_6kdkkhhW6O5WdIqW8Oc',
    appId: '1:433028474433:web:4ebf58a211ecef712dc8c0',
    messagingSenderId: '433028474433',
    projectId: 'fillup-755-2ceed',
    authDomain: 'fillup-755-2ceed.firebaseapp.com',
    storageBucket: 'fillup-755-2ceed.appspot.com',
    measurementId: 'G-0737WECFNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMbu4Ed3Fe6tK6xkjCXeFKPWDT6uAwiE4',
    appId: '1:433028474433:android:d3c130f941cdc4002dc8c0',
    messagingSenderId: '433028474433',
    projectId: 'fillup-755-2ceed',
    storageBucket: 'fillup-755-2ceed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Z3JrB7dw3Jhum0PGsm_VGemn90goWPY',
    appId: '1:433028474433:ios:928a07e2c26724c42dc8c0',
    messagingSenderId: '433028474433',
    projectId: 'fillup-755-2ceed',
    storageBucket: 'fillup-755-2ceed.appspot.com',
    iosClientId: '433028474433-4tmlhrf2t3f76642sde6vdjm4m6sh06s.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiilUpApp',
  );
}
